#!/usr/bin/env sh

# Copyright 2022 The Swarm Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This script generates Go code related to smart contracts.

readonly TARGET="${1}"
readonly VERSION="$(printf "%s" "${2}" | tr '.' '_')"

readonly STAKING_JSON="./artifacts/src/Staking.sol/StakeRegistry.json"
readonly STAKING_ABI="$(jq .abi "${STAKING_JSON}")"
readonly STAKING_BYTECODE="$(jq .bytecode "${STAKING_JSON}")"
readonly STAKING_DEPLOYED_BYTECODE="$(jq .deployedBytecode "${STAKING_JSON}")"

readonly POSTAGE_STAMP_JSON="./artifacts/src/PostageStamp.sol/PostageStamp.json"
readonly POSTAGE_STAMP_ABI="$(jq .abi "${POSTAGE_STAMP_JSON}")"
readonly POSTAGE_STAMP_BYTECODE="$(jq .bytecode "${POSTAGE_STAMP_JSON}")"
readonly POSTAGE_STAMP_DEPLOYED_BYTECODE="$(jq .deployedBytecode "${POSTAGE_STAMP_JSON}")"

readonly PRICE_ORACLE_JSON="./artifacts/src/PriceOracle.sol/PriceOracle.json"
readonly PRICE_ORACLE_ABI="$(jq .abi "${PRICE_ORACLE_JSON}")"
readonly PRICE_ORACLE_BYTECODE="$(jq .bytecode "${PRICE_ORACLE_JSON}")"
readonly PRICE_ORACLE_DEPLOYED_BYTECODE="$(jq .deployedBytecode "${PRICE_ORACLE_JSON}")"

readonly REDISTRIBUTION_JSON="./artifacts/src/Redistribution.sol/Redistribution.json"
readonly REDISTRIBUTION_ABI="$(jq .abi "${REDISTRIBUTION_JSON}")"
readonly REDISTRIBUTION_BYTECODE="$(jq .bytecode "${REDISTRIBUTION_JSON}")"
readonly REDISTRIBUTION_DEPLOYED_BYTECODE="$(jq .deployedBytecode "${REDISTRIBUTION_JSON}")"

cat << EOF > "${TARGET}"
// Copyright $(date +"%Y") The Swarm Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by codegen/generate_go_src.sh; DO NOT EDIT.
package abi

const (
	StakingABI${VERSION} = \`${STAKING_ABI}\`

	StakingBin${VERSION}         = ${STAKING_BYTECODE}
	StakingDeployedBin${VERSION} = ${STAKING_DEPLOYED_BYTECODE}
)

const (
	PostageStampABI${VERSION} = \`${POSTAGE_STAMP_ABI}\`

	PostageStampBin${VERSION}         = ${POSTAGE_STAMP_BYTECODE}
	PostageStampDeployedBin${VERSION} = ${POSTAGE_STAMP_DEPLOYED_BYTECODE}
)

const (
	PriceOracleABI${VERSION} = \`${PRICE_ORACLE_ABI}\`

	PriceOracleBin${VERSION}         = ${PRICE_ORACLE_BYTECODE}
	PriceOracleDeployedBin${VERSION} = ${PRICE_ORACLE_DEPLOYED_BYTECODE}
)

const (
	RedistributionABI${VERSION} = \`${REDISTRIBUTION_ABI}\`

	RedistributionBin${VERSION}         = ${REDISTRIBUTION_BYTECODE}
	RedistributionDeployedBin${VERSION} = ${REDISTRIBUTION_DEPLOYED_BYTECODE}
)
EOF

gofmt -w "${TARGET}"

exit $?
