// SPDX-License-Identifier: BSD-3-Clause
pragma solidity ^0.8.19;

import "../Redistribution.sol";
import "../interface/IPostageStamp.sol";
import "./EchidnaMocks.sol";
import "./RedistributionFixtureRandomness.sol";

contract EchidnaFixturePostageStampMock is IPostageStamp {
    struct BatchData {
        address owner;
        uint8 depth;
        uint8 bucketDepth;
        bool exists;
    }

    mapping(bytes32 => BatchData) internal batchData;

    uint256 public withdrawCalls;
    address public lastBeneficiary;
    uint256 public lastAmount;
    uint256 public pot = 1 ether;
    uint256 public validChunkCountValue = 1;

    function setBatch(bytes32 batchId, address owner, uint8 depth, uint8 bucketDepth) external {
        batchData[batchId] = BatchData({owner: owner, depth: depth, bucketDepth: bucketDepth, exists: true});
    }

    function seedPot(uint256 amount) external {
        pot += amount;
    }

    function withdraw(address beneficiary) external {
        withdrawCalls += 1;
        lastBeneficiary = beneficiary;
        lastAmount = pot;
        pot = 0;
    }

    function setPrice(uint256) external {}

    function validChunkCount() external view returns (uint256) {
        return validChunkCountValue;
    }

    function batchOwner(bytes32 batchId) external view returns (address) {
        return batchData[batchId].owner;
    }

    function batchDepth(bytes32 batchId) external view returns (uint8) {
        return batchData[batchId].depth;
    }

    function batchBucketDepth(bytes32 batchId) external view returns (uint8) {
        return batchData[batchId].bucketDepth;
    }

    function remainingBalance(bytes32 batchId) external view returns (uint256) {
        return batchData[batchId].exists ? 1 : 0;
    }

    function minimumInitialBalancePerChunk() external pure returns (uint256) {
        return 1;
    }

    function batches(
        bytes32 batchId
    )
        external
        view
        returns (
            address owner,
            uint8 depth,
            uint8 bucketDepth,
            bool immutableFlag,
            uint256 normalisedBalance,
            uint256 lastUpdatedBlockNumber
        )
    {
        BatchData memory b = batchData[batchId];
        if (!b.exists) {
            return (address(0), 0, 0, false, 0, 0);
        }
        return (b.owner, b.depth, b.bucketDepth, true, 1, 1);
    }
}

/// @notice Fixture-based Echidna harness for the real `claim()` verifier path.
/// @dev Uses hardcoded CAC/SOC proof bundles generated by the existing Hardhat tests.
contract EchidnaRedistributionRealClaimHarness {
    uint256 internal constant ROUND_LENGTH = 152;
    /// @dev Echidna evaluates properties on the deploy state (0 txs); defer strict checks until fuzzing runs.
    ///      Align with `echidna/echidna.yaml` `seqLen` (default 320): ~78 `act_*` calls ≈ first full sequence.
    ///      Must stay well below `testLimit` × `seqLen` so the strict property arms during a normal campaign.
    uint256 internal constant MIN_FUZZ_TXS_BEFORE_FIXTURE_E2E_REQUIRED = 25_000;

    uint8 internal constant FIXTURE_NONE = 0;
    uint8 internal constant FIXTURE_CAC = 1;
    uint8 internal constant FIXTURE_SOC = 2;

    address internal constant FIXTURE_BATCH_OWNER = 0x26234a2ad3bA8B398A762f279B792cfAcd536a3f;

    bytes32 internal constant FIXTURE_REVEAL_ANCHOR =
        0x3617319a054d772f909f7c479a2cebe5066e836a939412e32403c99029b92eff;
    bytes32 internal constant FIXTURE_CLAIM_SEED = 0xa4541cb5a0f209fed7c786aac6865922446ed57fc0dcf8ad07c17afcd3c5efb8;
    bytes32 internal constant FIXTURE_NONCE = 0xb5555b33b5555b33b5555b33b5555b33b5555b33b5555b33b5555b33b5555b33;

    bytes32 internal constant CAC_BATCH_ID = 0x5bee6f33f47fbe2c3ff4c853dbc95f1a6a4a4191a1a7e3ece999a76c2790a83f;
    bytes32 internal constant SOC_BATCH_ID = 0x6cccd65a68bc5f7c19a273e9567ebf4b968a13c9be74fc99ad90159730eff219;

    bytes32 internal constant CAC_HASH = 0xcf27be680f2dada5bcc45506997f54804e583650e48c28514ccc95234ef4f9f3;
    bytes32 internal constant SOC_HASH = 0x9a6afe770410c1bd7cdc1f324cfcf73ba1b85e3860d4594522456be4fe6b1d80;

    uint8 internal constant CAC_DEPTH = 1;
    uint8 internal constant SOC_DEPTH = 0;

    EchidnaStakeRegistryMock internal stakeMock;
    EchidnaFixturePostageStampMock internal stampMock;
    EchidnaPriceOracleMock internal oracleMock;
    Redistribution internal redist;

    uint8 internal activeFixtureKind;
    bytes32 internal activeHash;
    uint8 internal activeDepth;
    bool internal activeFixtureMutated;

    Redistribution.ChunkInclusionProof internal activeProof1;
    Redistribution.ChunkInclusionProof internal activeProof2;
    Redistribution.ChunkInclusionProof internal activeProofLast;

    bool internal commitPrepared;
    bool internal claimReady;
    uint64 internal preparedRound;

    bool internal lastClaimObserved;
    bool internal lastClaimExpectedSuccess;
    bool internal lastClaimSucceeded;
    uint256 internal withdrawCallsBeforeClaim;
    uint256 internal oracleCallsBeforeClaim;

    /// @dev Monotonic progress markers (never weakened by mutation helpers) so we can tell
    /// whether Echidna is only burning gas on early returns vs. driving the real pipeline.
    bool public fixtureCommitSucceededOnce;
    bool public fixtureRevealMadeClaimReadyOnce;
    bool public unmutatedFixtureClaimSucceededOnce;

    /// @dev Incremented once per `act_*` transaction (not per internal call).
    uint256 public fuzzActTxCount;

    modifier countFuzzTx() {
        unchecked {
            ++fuzzActTxCount;
        }
        _;
    }

    constructor() {
        stakeMock = new EchidnaStakeRegistryMock();
        stampMock = new EchidnaFixturePostageStampMock();
        oracleMock = new EchidnaPriceOracleMock();
        redist = new RedistributionFixtureRandomness(
            address(stakeMock),
            address(stampMock),
            address(oracleMock),
            FIXTURE_CLAIM_SEED
        );

        stampMock.setBatch(CAC_BATCH_ID, FIXTURE_BATCH_OWNER, 27, 16);
        stampMock.setBatch(SOC_BATCH_ID, FIXTURE_BATCH_OWNER, 27, 16);

        // The overlay is arbitrary for proof verification; we choose the fixture reveal anchor so
        // commit/reveal proximity is guaranteed once we reach the target round.
        stakeMock.setNode(address(this), FIXTURE_REVEAL_ANCHOR, 0, 1e18, 1);
        _useCacFixture();
    }

    function act_tick() external countFuzzTx {}

    function act_useCacFixture() external countFuzzTx {
        _useCacFixture();
    }

    function act_useSocFixture() external countFuzzTx {
        _useSocFixture();
    }

    function act_seedPot(uint256 amount) external countFuzzTx {
        stampMock.seedPot((amount % 1e24) + 1);
    }

    function act_prepareFixtureCommit() external countFuzzTx {
        _clearLastClaim();
        if (activeFixtureKind == FIXTURE_NONE) return;
        if (!redist.currentPhaseCommit()) return;
        // Pristine `seed == 0` and no prior reveals: anchor hits this iff `currentRound() == 4`.
        if (redist.currentRoundAnchor() != FIXTURE_REVEAL_ANCHOR) return;
        if (block.number % ROUND_LENGTH == (ROUND_LENGTH / 4) - 1) return;

        stakeMock.setNode(address(this), FIXTURE_REVEAL_ANCHOR, 0, 1e18, _backdateLastUpdated());

        bytes32 obfuscated = redist.wrapCommit(FIXTURE_REVEAL_ANCHOR, activeDepth, activeHash, FIXTURE_NONCE);
        (bool ok, ) = address(redist).call(
            abi.encodeWithSelector(redist.commit.selector, obfuscated, redist.currentRound())
        );
        if (!ok) return;

        fixtureCommitSucceededOnce = true;
        commitPrepared = true;
        claimReady = false;
        preparedRound = redist.currentRound();
    }

    function act_prepareFixtureReveal() external countFuzzTx {
        _clearLastClaim();
        if (!commitPrepared) return;
        if (!redist.currentPhaseReveal()) return;
        if (redist.currentRound() != preparedRound) return;
        if (redist.currentCommitRound() != preparedRound) return;

        (bool ok, ) = address(redist).call(
            abi.encodeWithSelector(redist.reveal.selector, activeDepth, activeHash, FIXTURE_NONCE)
        );
        if (!ok) return;

        claimReady = redist.currentSeed() == FIXTURE_CLAIM_SEED;
        if (claimReady) fixtureRevealMadeClaimReadyOnce = true;
    }

    function act_claimActiveFixture() external countFuzzTx {
        _clearLastClaim();
        if (!claimReady) return;
        if (!redist.currentPhaseClaim()) return;
        if (redist.currentRound() != preparedRound) return;

        lastClaimObserved = true;
        lastClaimExpectedSuccess = !activeFixtureMutated;
        withdrawCallsBeforeClaim = stampMock.withdrawCalls();
        oracleCallsBeforeClaim = oracleMock.calls();

        (lastClaimSucceeded, ) = address(redist).call(
            abi.encodeWithSelector(redist.claim.selector, activeProof1, activeProof2, activeProofLast)
        );

        if (lastClaimSucceeded && lastClaimExpectedSuccess) {
            unmutatedFixtureClaimSucceededOnce = true;
        }
    }

    function act_mutateReserveCommitmentRoot(bytes32 replacement) external countFuzzTx {
        if (activeFixtureKind == FIXTURE_NONE || activeProof1.proofSegments.length == 0) return;
        activeProof1.proofSegments[0] = _tweak(replacement);
        activeFixtureMutated = true;
        _clearLastClaim();
    }

    function act_mutateOriginalChunkBranch(bytes32 replacement) external countFuzzTx {
        if (activeFixtureKind == FIXTURE_NONE || activeProof1.proofSegments2.length < 2) return;
        activeProof1.proofSegments2[1] = _tweak(replacement);
        activeFixtureMutated = true;
        _clearLastClaim();
    }

    function act_mutateTransformedChunkBranch(bytes32 replacement) external countFuzzTx {
        if (activeFixtureKind == FIXTURE_NONE || activeProof1.proofSegments3.length < 2) return;
        activeProof1.proofSegments3[1] = _tweak(replacement);
        activeFixtureMutated = true;
        _clearLastClaim();
    }

    function act_mutatePostageIndexLow(uint32 lowWord) external countFuzzTx {
        if (activeFixtureKind == FIXTURE_NONE) return;
        uint64 current = activeProof1.postageProof.index;
        uint64 next = (current & 0xffffffff00000000) | uint64(lowWord);
        if (next == current) next ^= 1;
        activeProof1.postageProof.index = next;
        activeFixtureMutated = true;
        _clearLastClaim();
    }

    function act_mutatePostageIndexHigh(uint32 highWord) external countFuzzTx {
        if (activeFixtureKind == FIXTURE_NONE) return;
        uint64 current = activeProof1.postageProof.index;
        uint64 next = (uint64(highWord) << 32) | (current & 0xffffffff);
        if (next == current) next ^= uint64(1) << 32;
        activeProof1.postageProof.index = next;
        activeFixtureMutated = true;
        _clearLastClaim();
    }

    function act_mutateSocIdentifier(bytes32 replacement) external countFuzzTx {
        if (activeFixtureKind != FIXTURE_SOC || activeProof1.socProof.length == 0) return;
        activeProof1.socProof[0].identifier = _tweak(replacement);
        activeFixtureMutated = true;
        _clearLastClaim();
    }

    function echidna_unmutated_fixture_claim_succeeds() external view returns (bool) {
        if (!lastClaimObserved) return true;
        if (!lastClaimExpectedSuccess) return true;
        return lastClaimSucceeded;
    }

    function echidna_mutated_fixture_claim_does_not_succeed() external view returns (bool) {
        if (!lastClaimObserved) return true;
        if (lastClaimExpectedSuccess) return true;
        return !lastClaimSucceeded;
    }

    function echidna_successful_real_claim_effects_hold() external view returns (bool) {
        if (!lastClaimObserved || !lastClaimExpectedSuccess || !lastClaimSucceeded) return true;
        if (stampMock.withdrawCalls() != withdrawCallsBeforeClaim + 1) return false;
        if (oracleMock.calls() != oracleCallsBeforeClaim + 1) return false;
        if (stampMock.lastBeneficiary() != address(this)) return false;
        if (stampMock.pot() != 0) return false;
        if (redist.currentClaimRound() != preparedRound) return false;
        return true;
    }

    /// @notice Non-vacuous over a full campaign: after warmup, requires at least one successful unmutated fixture `claim`.
    /// @dev Lower `MIN_FUZZ_TXS_BEFORE_FIXTURE_E2E_REQUIRED` only for short smoke runs; defaults assume `echidna.yaml` (60k × 320).
    function echidna_unmutated_fixture_end_to_end_must_succeed_at_least_once() external view returns (bool) {
        if (fuzzActTxCount < MIN_FUZZ_TXS_BEFORE_FIXTURE_E2E_REQUIRED) return true;
        return unmutatedFixtureClaimSucceededOnce;
    }

    function _useCacFixture() internal {
        _resetFixtureState();
        activeFixtureKind = FIXTURE_CAC;
        activeHash = CAC_HASH;
        activeDepth = CAC_DEPTH;
        _writeProof(activeProof1, _cacProof1());
        _writeProof(activeProof2, _cacProof2());
        _writeProof(activeProofLast, _cacProofLast());
    }

    function _useSocFixture() internal {
        _resetFixtureState();
        activeFixtureKind = FIXTURE_SOC;
        activeHash = SOC_HASH;
        activeDepth = SOC_DEPTH;
        _writeProof(activeProof1, _socProof1());
        _writeProof(activeProof2, _socProof2());
        _writeProof(activeProofLast, _socProofLast());
    }

    function _resetFixtureState() internal {
        delete activeProof1;
        delete activeProof2;
        delete activeProofLast;
        activeFixtureMutated = false;
        commitPrepared = false;
        claimReady = false;
        preparedRound = 0;
        _clearLastClaim();
    }

    function _clearLastClaim() internal {
        lastClaimObserved = false;
        lastClaimExpectedSuccess = false;
        lastClaimSucceeded = false;
        withdrawCallsBeforeClaim = 0;
        oracleCallsBeforeClaim = 0;
    }

    function _backdateLastUpdated() internal view returns (uint256) {
        uint256 twoRounds = 2 * ROUND_LENGTH;
        if (block.number > twoRounds + 1) return block.number - twoRounds - 1;
        return 1;
    }

    function _tweak(bytes32 value) internal pure returns (bytes32) {
        if (value == bytes32(0)) return bytes32(uint256(1));
        return value;
    }

    function _writeProof(
        Redistribution.ChunkInclusionProof storage dst,
        Redistribution.ChunkInclusionProof memory src
    ) internal {
        delete dst.proofSegments;
        delete dst.proveSegment;
        delete dst.proofSegments2;
        delete dst.proveSegment2;
        delete dst.chunkSpan;
        delete dst.proofSegments3;
        delete dst.postageProof;
        delete dst.socProof;

        _writeBytes32Array(dst.proofSegments, src.proofSegments);
        dst.proveSegment = src.proveSegment;
        _writeBytes32Array(dst.proofSegments2, src.proofSegments2);
        dst.proveSegment2 = src.proveSegment2;
        dst.chunkSpan = src.chunkSpan;
        _writeBytes32Array(dst.proofSegments3, src.proofSegments3);

        dst.postageProof.signature = src.postageProof.signature;
        dst.postageProof.postageId = src.postageProof.postageId;
        dst.postageProof.index = src.postageProof.index;
        dst.postageProof.timeStamp = src.postageProof.timeStamp;

        for (uint256 i = 0; i < src.socProof.length; i++) {
            dst.socProof.push();
            dst.socProof[i].signer = src.socProof[i].signer;
            dst.socProof[i].signature = src.socProof[i].signature;
            dst.socProof[i].identifier = src.socProof[i].identifier;
            dst.socProof[i].chunkAddr = src.socProof[i].chunkAddr;
        }
    }

    function _writeBytes32Array(bytes32[] storage dst, bytes32[] memory src) internal {
        for (uint256 i = 0; i < src.length; i++) {
            dst.push(src[i]);
        }
    }

    function _arr7(
        bytes32 a0,
        bytes32 a1,
        bytes32 a2,
        bytes32 a3,
        bytes32 a4,
        bytes32 a5,
        bytes32 a6
    ) internal pure returns (bytes32[] memory arr) {
        arr = new bytes32[](7);
        arr[0] = a0;
        arr[1] = a1;
        arr[2] = a2;
        arr[3] = a3;
        arr[4] = a4;
        arr[5] = a5;
        arr[6] = a6;
    }

    function _cacProof1() internal pure returns (Redistribution.ChunkInclusionProof memory p) {
        p.proofSegments = _arr7(
            0x000057515f1f37c0136197a45bd50b4618e3ebe272c4fb34b7f00e8972b84630,
            0x24d4e8fa9840ee525cf13d85ec07ad6b6ac88a180c5e420a7e57f9a3bf0a0578,
            0x85e4c229f557648ecbd01e0d768a1786bd3df8bb248a395c5768fad9d8d56f74,
            0x19042aeaca66e2bf5e961ff1429b51d0b566700e94154d3ff2addea8910a857f,
            0x931e95ed8ea3efe7c961602b8b7888b59947124f190da163b85246c1d8dc28bc,
            0x0eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2d,
            0x887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968
        );
        p.proveSegment = 0x78fbc965b296a7e146ae2cfb03f4df22a84779078538905dde74327bf4e36545;
        p.proofSegments2 = _arr7(
            0x6e21b55f5f30ea3d77ca7ee24fe43928f309f19916978a98eb75bd8dfbf9e9fb,
            0xe82ab3bce42ee51c670eadc57c5d7eab70a902e977ac2a820d82d1910b49c30a,
            0x0abb1479acb3314a30ecdc03016e6ef8900aa48882885f33918b8740d7766e26,
            0xb07cfba2224b8d59a81006711d8a4c1b8e342e7bfc8355cb7a1907793663b7cb,
            0xecf121c97385aed4648d1eca4eda8b7d4d1e7094c9a29b44ec8cd759b562bba8,
            0x03dac69fb24d1c455fe32e866dec762944d198a7fb38aa5744030a8b0157edf1,
            0x6eb22b1022d18748bd1f3b2f0afe6ec82d7457406012ea91728452602ebc44b2
        );
        p.proveSegment2 = 0x575c434071a58a272ed3d3c9c73782c66b680650540409b53c05db21a21db577;
        p.chunkSpan = 4096;
        p.proofSegments3 = _arr7(
            0x6e21b55f5f30ea3d77ca7ee24fe43928f309f19916978a98eb75bd8dfbf9e9fb,
            0x3ff0f0743b3d169981cc5f67cbcf8725917e43dd4aea9bfee4e22abe4d18ecf9,
            0x50ffd8a56337e576f0b56c2563082dc4776d099503479bb918548f21b0d55daa,
            0x3ccc3ad084a22f20f06e9b388ddcfeda2c6781f9c9f0e4e6c896ab78e9c1270e,
            0xb5fdcfb93b778f5ae8fa2564633e31f195b518c63d00831d9a57556ac43760db,
            0x04ad7a29fe63d0373e47f0184950cb538dd82482a23c757095b4adac2a5a9357,
            0xc2ef7172b9c978b3e579a3424d03db71f907932fc9b9b031bfa5c7dd9713ba64
        );
        p.postageProof = Redistribution.PostageProof({
            signature: hex"f6b2fbdaf5a59b55303e98d9cfb8f5d730cd4cec601abf28f62cbd2c2e3f0dcc3d2c82144b2332c52961290b3a64dd25231fc5afa3ad31541c6a0a64ee1954ac1c",
            postageId: CAC_BATCH_ID,
            index: 0x000078fb00000017,
            timeStamp: 0x1785462106d88f33
        });
        p.socProof = new Redistribution.SOCProof[](0);
    }

    function _cacProof2() internal pure returns (Redistribution.ChunkInclusionProof memory p) {
        p.proofSegments = _arr7(
            0x00009dab88dcb65c9eb3028506d26b918b33b740d689e2c8d215a675c4fa8891,
            0xf85d5e81948dbb24f33bbf6af7efceb547c47d5a64e8b11f676b893751a1bfd0,
            0x7d1b3e453e4c08496f30ed71a866ac28916e27cd3885a16a961d1dc87c8befa8,
            0xbb651df2741f07c6aed8a68af8d08c32ab556bb05403473dc6ab3d0d68087785,
            0x931e95ed8ea3efe7c961602b8b7888b59947124f190da163b85246c1d8dc28bc,
            0x0eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2d,
            0x887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968
        );
        p.proveSegment = 0x724fc91ed7318f5c04ce30d33cc9444eb4937974285af8cbc87097a40edccd09;
        p.proofSegments2 = _arr7(
            0xa5853628094e0da25bc9f8ef2e56e0b43367e8f1644781eab6f0d8adceb37de1,
            0x8c7699a136deeef563d257530044ad3421ebea67faadbe5670c6a53b1da95681,
            0x37141d349d016b61787ea8d50d246d40d5c47dafd2b618150eb2735c9e147336,
            0xd620b8cba4e9c6d0258d900756f0156a92baf7093fd71101c2205a1ee11484a5,
            0x33482c710b3838c0db16022f226aa1aa5dc449d7b086e42e39220ef38cc8b9b9,
            0xf345ba3b2bae408d46585568803ba75a5b551701f488172449455700ec1a0f97,
            0x634dded701a03c7b13b8d3180df87fbbfa185f5f9b8dafad09d2f297a2b45e31
        );
        p.proveSegment2 = 0xeff9bac0c51082ff8d4380bf8cdca4fa9c20bcdc4190f2a2f3a999726d77f9f1;
        p.chunkSpan = 4096;
        p.proofSegments3 = _arr7(
            0xa5853628094e0da25bc9f8ef2e56e0b43367e8f1644781eab6f0d8adceb37de1,
            0xd453c8dca4cf42a72f1839330b5714b1f06eb476a4085d6dd65725b39544ed5c,
            0x73dc1145525816ba07842f433c81e2d9afd088fbff91b41f8378e04ecdccd2c0,
            0xff12b1e18bca6906208368d3572f6bc8c1ea638621c4a448424e1a190ad2aadd,
            0x3e6d67361b3762a2b0a15cf3af86681bbead5ee282c19dab5fa96df5b398685b,
            0x6bd935f8dcbd319861b13f1c0283d699b454bb20b5492393fec71ba6bc67d8a7,
            0x5bcf6be70e14ef138cb6f686163cf19406f943312679f1ae3f9573f0205dcdb9
        );
        p.postageProof = Redistribution.PostageProof({
            signature: hex"0d683b47c584585f00462c943c745d317d6354841b5fa78e8f50793e01e0f0ee7f6cb4a320e45382b92ecdbe6e3db380e309ce1279c8b15a2ab6e09a94f752f21c",
            postageId: CAC_BATCH_ID,
            index: 0x0000724f00000023,
            timeStamp: 0x178551f31887a7e0
        });
        p.socProof = new Redistribution.SOCProof[](0);
    }

    function _cacProofLast() internal pure returns (Redistribution.ChunkInclusionProof memory p) {
        p.proofSegments = _arr7(
            0x0000a386b3d729becb0f7c5a938eff58dc4c5b45cb48876c0aabe38b3ec61511,
            0x13b90286a980a173a93f8d99f91eceaa5cfba622b787d7e47d799c93b728d8f0,
            0xe9d29a6a168d71c4601b5a03f0250ffff95dea7a89a0eeea57270fc14b5e28f0,
            0xbb651df2741f07c6aed8a68af8d08c32ab556bb05403473dc6ab3d0d68087785,
            0x931e95ed8ea3efe7c961602b8b7888b59947124f190da163b85246c1d8dc28bc,
            0x0eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2d,
            0x887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968
        );
        p.proveSegment = 0x7cfd4723785c35784b3a9fc7e9627e05b4ba2d175bb27cc36457c5abfa3487b7;
        p.proofSegments2 = _arr7(
            0x09b6a9039fd92221244a46d66c5daa640ce2b4df4d8664c60393c006c8466241,
            0x926473068fb33428e2ba2b5ef06a4030f7d28840b3f6c39ff39e5c29c3c3d572,
            0xe280f788a94a73ba383aef1a375ce551c50397457631b7f192a094cf93754df2,
            0x7cae69170533f9610e78b1872811feb26765bedef8194232d1f83b3d6c4f0550,
            0x45603497bee8141ce3a62fe57500d1857e4c9be9c88a435e688f9d79031ac200,
            0xa5d5238098387e9fb8a0d2f834f06e32a941949cc8981e7001b4f237540dc72d,
            0x66854bd0e7aecd6abbe45b5f65944b54cc2cf6162ea821d03c1a766997d047ba
        );
        p.proveSegment2 = 0x318aa90994bc17e443e67fd083d8ab251c1d17ced4e8ab983ddf02890d002605;
        p.chunkSpan = 4096;
        p.proofSegments3 = _arr7(
            0x09b6a9039fd92221244a46d66c5daa640ce2b4df4d8664c60393c006c8466241,
            0x1243fc9df50961e8024851eb386470b4fe740a696c4dc5f06ac3ae268abaaf93,
            0x1a3bb6274281c057e5c5cf67316a36919c7796dc2db102137f936b7641cbe1ff,
            0x43047f57784dc25563f3049ebf918d8a8da731a2c98c6d8ea1883dc0a3e815b2,
            0x4a28eaa92b6b420cfd863f49e69ce3399f239d4c708a9747f7fdf2d4435605e4,
            0x4f3dd2aad4e6357ebc9d0bec8107601b7203dd32c279036a37b1823f976d3172,
            0xfe68d10d01f82c29eb44448659fed31a5f89d49dc7a553f23be89cc67d5bdece
        );
        p.postageProof = Redistribution.PostageProof({
            signature: hex"185e49bdb4c3a50178d8e14da8f402b0df7f7608b6658e92e6e0c2dc1a653e7c14e8e9d4ccd743019ed78bf6ad1733f065ec7540f717dea4d0ae389bb15bc2841c",
            postageId: CAC_BATCH_ID,
            index: 0x00007cfd00000020,
            timeStamp: 0x178548a18495b42a
        });
        p.socProof = new Redistribution.SOCProof[](0);
    }

    function _socProof1() internal pure returns (Redistribution.ChunkInclusionProof memory p) {
        p.proofSegments = _arr7(
            0x00007f4036a4e72c49e6d1c90889d604194485062dbf05143335da5824972c9d,
            0x13cba79217e582fe2ddd0b8edbf6293ef98635bee9c76cb254952d468c031d08,
            0x015507653c37aec258fd3ca4fbf8dc3741986697cb1eb42c3245c9314e6dd272,
            0x55f1711fe7f802faf26d24ff80ee9dc5d3881972d9ce070b81d1eaee387ff62f,
            0xcbfd07f8af7baa634e60c2b296ef08347bd639023ce674b8e00415173c78951a,
            0x0eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2d,
            0x887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968
        );
        p.proveSegment = 0x71842d5d67339a6a0f096c5a9983308d4b6596baeb016696b3512c6fa95f9d89;
        p.proofSegments2 = _arr7(
            bytes32(0),
            0xad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5,
            0xb4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d30,
            0x21ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85,
            0xe58769b32a1beaf1ea27375a44095a0d1fb664ce2dd358e7fcbfb78c26a19344,
            0xf583106353614658f33a983eeead8a2d4d20b7b6d90227eaeff9a01bb5ffb909,
            0x887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968
        );
        p.proveSegment2 = bytes32(0);
        p.chunkSpan = 3;
        p.proofSegments3 = _arr7(
            bytes32(0),
            0x67b9c124b55528ea0f5bcb5db716513af90deeb860e6ffd4b04ff0cd5cf68fb1,
            0xd769d9f556cb6ff5100712c5a9ffd2872bf7469a78f8ec96815173473857b57b,
            0x92a902cf7bbe37528d886bfb4c4e304572b65920a7e8fa413bc336031c7b10e9,
            0x21f21466fe5abe61950d97653c028a940ba863ac39b9ad8de388a159c0d81651,
            0x19134f518cf4e7b0a4eb34cfd97e6fe201c97b4d255330ca226b22b93a224389,
            0xb6c8532228cd44b9e59febed68f8038e1059fa779813d6bfe30dd9f150ab6b99
        );
        p.postageProof = Redistribution.PostageProof({
            signature: hex"9d6a824eee86bc6d107b1ff917f7bacd9004751000e75f34dc78a0ef4230685935fb0808494583a4c62284562bacac394534bb83cb837034c1a5d2034679ce681c",
            postageId: SOC_BATCH_ID,
            index: 0x0000718400000000,
            timeStamp: 0x1787d532f407197a
        });
        p.socProof = new Redistribution.SOCProof[](1);
        p.socProof[0] = Redistribution.SOCProof({
            signer: 0x316104Fe34dF9A02d8f93412A2e4b0973D63cC31,
            signature: hex"e3d66649291e1e805b7be2a2e6585eca7df8a0e10c960230f55b1fec83805c032955d6708cde4a7b0d205201b9fd0a6e484174d56903ddce34b356d3a691fad91b",
            identifier: 0x0000000000000000000000000003042500000000000000000000000000000000,
            chunkAddr: 0x2387e8e7d8a48c2a9339c97c1dc3461a9a7aa07e994c5cb8b38fd7c1b3e6ea48
        });
    }

    function _socProof2() internal pure returns (Redistribution.ChunkInclusionProof memory p) {
        p.proofSegments = _arr7(
            0x000092031489ee631d69963039604310bc1a6fc1762bc98bf26ac4b8e2257595,
            0x05bb617234eeb399cfc1e53ab8aec230c5c60f01c51f28cf255227dc87973b3d,
            0x748eb1b53190df4ec58a8fcc36d50180ab307925f3b3b3c98f7196ca97362a25,
            0x0a3cea527135006ec5468fcd91f265775635fdbb0d2d377542fd2c89cc866534,
            0xcbfd07f8af7baa634e60c2b296ef08347bd639023ce674b8e00415173c78951a,
            0x0eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2d,
            0x887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968
        );
        p.proveSegment = 0x7f68a817240e4e5d7941948de6c252c4b34c8b39b08e2d519ca35e68519d7cae;
        p.proofSegments2 = _arr7(
            bytes32(0),
            0xad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5,
            0xb4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d30,
            0x21ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85,
            0xe58769b32a1beaf1ea27375a44095a0d1fb664ce2dd358e7fcbfb78c26a19344,
            0xf583106353614658f33a983eeead8a2d4d20b7b6d90227eaeff9a01bb5ffb909,
            0x887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968
        );
        p.proveSegment2 = bytes32(0);
        p.chunkSpan = 3;
        p.proofSegments3 = _arr7(
            bytes32(0),
            0x67b9c124b55528ea0f5bcb5db716513af90deeb860e6ffd4b04ff0cd5cf68fb1,
            0xd769d9f556cb6ff5100712c5a9ffd2872bf7469a78f8ec96815173473857b57b,
            0x92a902cf7bbe37528d886bfb4c4e304572b65920a7e8fa413bc336031c7b10e9,
            0x21f21466fe5abe61950d97653c028a940ba863ac39b9ad8de388a159c0d81651,
            0x19134f518cf4e7b0a4eb34cfd97e6fe201c97b4d255330ca226b22b93a224389,
            0xb6c8532228cd44b9e59febed68f8038e1059fa779813d6bfe30dd9f150ab6b99
        );
        p.postageProof = Redistribution.PostageProof({
            signature: hex"5c14de70eab0f55b06d7f3cb474f37786b36930b2652f96dcdc33305c23f7861196d03b7e68216184ed883aac1538af8a33401e989c328f31bc03f7d0f5ebaf21b",
            postageId: SOC_BATCH_ID,
            index: 0x00007f6800000000,
            timeStamp: 0x1787d532e7720d47
        });
        p.socProof = new Redistribution.SOCProof[](1);
        p.socProof[0] = Redistribution.SOCProof({
            signer: 0x316104Fe34dF9A02d8f93412A2e4b0973D63cC31,
            signature: hex"83404406b178c034da21949e4aff2f371ba8bac0ceb373263160007ba01230776ffa188dfa8abe15b0e63fe56fd0ecbddd3cdfd36abaa7f1696f31a5dd64a6731b",
            identifier: 0x000000000000000000000000000000000000000000000000000124a900000000,
            chunkAddr: 0x2387e8e7d8a48c2a9339c97c1dc3461a9a7aa07e994c5cb8b38fd7c1b3e6ea48
        });
    }

    function _socProofLast() internal pure returns (Redistribution.ChunkInclusionProof memory p) {
        p.proofSegments = _arr7(
            0x0000abb415738db50ec1b83a9f670130c158ab7001e9b452bd928f3eb715f432,
            0xbe6083fead93f365617744e0cfceed4c83c1cdf25c54f45a9b39e913ac61de72,
            0x5396f7a2a7d5d0c6c33ceae5fd2089fd38e1f5e03131bf80257773da087c0fc2,
            0x0a3cea527135006ec5468fcd91f265775635fdbb0d2d377542fd2c89cc866534,
            0xcbfd07f8af7baa634e60c2b296ef08347bd639023ce674b8e00415173c78951a,
            0x0eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2d,
            0x887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968
        );
        p.proveSegment = 0x465f8c4bd9089cf0315ec603d5ad81ec27ebd4056ea714c91e4fc1c2bbd03a08;
        p.proofSegments2 = _arr7(
            bytes32(0),
            0xad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5,
            0xb4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d30,
            0x21ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85,
            0xe58769b32a1beaf1ea27375a44095a0d1fb664ce2dd358e7fcbfb78c26a19344,
            0xf583106353614658f33a983eeead8a2d4d20b7b6d90227eaeff9a01bb5ffb909,
            0x887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968
        );
        p.proveSegment2 = bytes32(0);
        p.chunkSpan = 3;
        p.proofSegments3 = _arr7(
            bytes32(0),
            0x67b9c124b55528ea0f5bcb5db716513af90deeb860e6ffd4b04ff0cd5cf68fb1,
            0xd769d9f556cb6ff5100712c5a9ffd2872bf7469a78f8ec96815173473857b57b,
            0x92a902cf7bbe37528d886bfb4c4e304572b65920a7e8fa413bc336031c7b10e9,
            0x21f21466fe5abe61950d97653c028a940ba863ac39b9ad8de388a159c0d81651,
            0x19134f518cf4e7b0a4eb34cfd97e6fe201c97b4d255330ca226b22b93a224389,
            0xb6c8532228cd44b9e59febed68f8038e1059fa779813d6bfe30dd9f150ab6b99
        );
        p.postageProof = Redistribution.PostageProof({
            signature: hex"befadfdceb1076fe27cc08152aac4f91b5245f4e911a323c81eef79faeff7a652de99192554e37d99d615d1a693df3632d0b660cba6285f79ca29c8f457359761c",
            postageId: SOC_BATCH_ID,
            index: 0x0000465f00000000,
            timeStamp: 0x1787d532e3d9be0f
        });
        p.socProof = new Redistribution.SOCProof[](1);
        p.socProof[0] = Redistribution.SOCProof({
            signer: 0x316104Fe34dF9A02d8f93412A2e4b0973D63cC31,
            signature: hex"fb3d1660aa1a42bb342073914c4a74f098a0fab772baec7f18f60154feeecb35625f1b2b6d101902c0cc62abbf7ab71c5ddacb786a2841ce36bd2e3534566b5d1c",
            identifier: 0x0000000000000000000054040000000000000000000000000000000000000000,
            chunkAddr: 0x2387e8e7d8a48c2a9339c97c1dc3461a9a7aa07e994c5cb8b38fd7c1b3e6ea48
        });
    }
}
